### ISSUE TITLE
Création de l'arbre

### ISSUE THREAD

**Issue by alexstraubhaar** [alexstraubhaar/Compilateur#1]
Une fois toute la grammaire implémentée, créer l'arbre syntaxique (plus sur du terme lol) avec AST.
- [x] Find out why you can't put multiple structures => adding a ´~' after structures fixes the bug.
- [x] SMWYG
- [x] whale
- [x] jeez
- [x] wubbalubbadubdubs
- [x] cando
- [x] schwift
- [x] cases
- [x] conditions
- [x] assignation
- [x] assignation w/ var type
- [x] reassignation

**Comment by megaturbo** [comment]
looks fine

**Comment by megaturbo** [comment]
- [x] meeseeks
